[build]
  command = "pnpm install && pnpm build"
  publish = "./build"
  
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "pnpm dev"
  port = 5173