[build]
  command = "pnpm build"
  publish = "build"
  
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "pnpm dev"
  port = 5173